name: mobile
description: "AI SOS Guardian Mobile Client"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Default Flutter icons
  cupertino_icons: ^1.0.8

  # --- Phase 1: Communication ---
  geolocator: ^14.0.2       # GPS Location access
  url_launcher: ^6.3.2      # SMS Fallback triggering
  http: ^1.6.0              # REST API connectivity

  # --- Phase 2: Security & Persistence (NEW) ---
  cryptography: ^2.9.0      # X25519 Key generation & signing
  shared_preferences: ^2.5.4 # Persisting Identity Keys on device
  # --- Phase 2: Ghost Mode BWAHAHA ---
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^20.1.0
  permission_handler: ^12.0.1
  sensors_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
